### ISSUE TITLE
dma card

### ISSUE THREAD

**Issue by RaliVault** [IntelSDM/RustDmaCheat#10]
what do you use dma card?
please official shop link!

**Comment by IntelSDM** [comment]
https://lightingz.store/products/lightingzdma-ndma-usb3-0-190mb-s-with-custom-firmware
https://shop.lambdaconcept.com/home/50-screamer-pcie-squirrel.html
Lightning is a new innovative company that has really cheap products and a good support team.
Lambda is more expensive, less support but I have had one of their cards for a very long time and It works well enough. 
Neither come with custom firmware.

**Comment by RaliVault** [comment]
i see.
what is custom fw?

**Comment by arlohewitt** [comment]
> Author

Custom firmware is what stops anticheats from banning you

**Comment by RaliVault** [comment]
ohh thx for teaching :+1:
