### ISSUE TITLE
Error on 25 line in BasePlayer.cpp  (delete BaseMovementInstance;) 

### ISSUE THREAD

**Issue by MaRf1Mm** [IntelSDM/RustDmaCheat#14]
Good day, everything was working fine for 2 weeks, but after the recent update, this error started to appear (Exception thrown at 0x00007FFE20935BB6 (ntdll.dll) in RustDMA.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.) as well as (Unhandled exception at 0x00007FFE20A0F279 (ntdll.dll) in RustDMA.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFE20A787F0)). After which the console closes. Checking with the debugger, the error occurs on line 25 in BasePlayer.cpp. I checked and rechecked the offsets and everything from .scripts, they match with the recent game update. I've been trying to solve the problem for 4 hours and decided to seek help here, I would be grateful for any advice.

**Comment by MaRf1Mm** [comment]
> Sadly, my DMA card isn't exactly working right now. I pushed an update to address this issue. I changed the BaseMovementInstance to be a smart pointer, which it should have already been, so there shouldn't be an error deconstructing it, it will do it automatically. I also updated whatever offsets and classes I could see were outdated. All of the BasePlayer fields seemed to be shifted by 16 bits(0xA). Since I couldn't test; some stuff could still be outdated.

No problem, take your time, I didn't even expect such a quick response. I'll go check the update and report back here if anything changes.

**Comment by MaRf1Mm** [comment]
So, first off, this fixed the error and everything is now loading correctly. However, now every time the console outputs BAD DTB: PID=27548 DTB=40000007587a7000, errors pop up on the screen. Any ideas?
![image](https://github.com/IntelSDM/RustDmaCheat/assets/107577770/16d34264-3c80-4821-8c9e-bd3b824a123d)

**Comment by IntelSDM** [comment]
The bad PID issue is fine, don't worry about it.
The text on the screen is saying that the console system interaction is incorrect. I will quickly look into that.
