### ISSUE TITLE
python isnt been found and the scatter bytes wont read 

### ISSUE THREAD

**Issue by blackoutservices** [IntelSDM/RustDMACheat#15]
python isnt been found and the scatter bytes wont read

**Comment by blackoutservices** [comment]
i sent you a request on discord, my discord is :g5x5

**Comment by MaRf1Mm** [comment]
> python isnt been found and the scatter bytes wont read

If something is not working, just delete the "Release" folder and perform a fresh installation.
If the issue persists, you can try to fix it yourself. Build the project as Debug, run the check, and see where the error occurs. If you're unable to do it on your own, there is plenty of information available online regarding such errors, or as a last resort, you can ask ChatGPT for assistance.

Still working after the update:
![image](https://github.com/IntelSDM/RustDmaCheat/assets/107577770/475d7a35-ed40-4b69-bd82-1bd11da988f1)

**Comment by MaRf1Mm** [comment]
Also, if anyone needs it, I have created a small project that converts all the required signatures from script.json into HEX format for faster updates after Rust has been updated.
https://github.com/MaRf1Mm/Script.json-Converter-for-Rust

**Comment by IntelSDM** [comment]
Sounds like it is outdated, you need to update it. The issues regarding python will require you to just reinstall and set the system directory for python.
