### ISSUE TITLE
question regarding offsets

### ISSUE THREAD

**Issue by Aiden-10** [IntelSDM/RustDMACheat#16]
How do you find the value of the static field offsets for examole in TODSky.h StaticField = 0xB8 how does one find that and where does it come from aswell as intance = 0. Thanks for the help and great source!

**Comment by IntelSDM** [comment]
The 0xB8 To access the static field contents is because unity creates a Heap at 0xB8, Think of it like an instance of the class for the static access of it. It will always be at 0xB8 in any static class. 
Whenever I have an instance set to 0 it is because I am going to get the instance from a field in the static class so I just set it to 0 until it is read.

**Comment by Aiden-10** [comment]
Using your project, I was able to get all the information I need to make a radar cheat. I am having trouble however including files in the solution. I have never used pch but whenever I try and include for example imgui I get this error which prevents me from building: 

"Error C2857 '#include' statement specified with the /Ycpch.h command-line option was not found in the source file"

Currently I made a new folder inside of misc named gui with all the imgui files I need to create a dx11 window. But when for example I #include "gui/imgui.h" I get this error and have tried for hours to fix it.

Thanks for the help

**Comment by IntelSDM** [comment]
With a PCH you need to #include "pch.h" as the first line of any c++ file.

**Comment by Aiden-10** [comment]
Thanks that fixed the problem. Sorry for so many questions this will be my last. For my radar cheat I have started looping through the networkables and grabbing the positions of all ores, hemp, and TCs etc. The problem arises when I want to display all the positions on the window. Currently I re-read base networkables every 15 seconds in the main loop and then store all of the pointers to position and name and read from that. But next time I loop networkables it causes some lag so how would you go about this?

thanks
