### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Yangaaa137** [IntelSDM/RustDMACheat#17]
![157842-fe95ffc90bc7d3d18f24f90e998b5e22](https://github.com/IntelSDM/RustDmaCheat/assets/62979922/0fa0d18b-b9d9-4c2b-96f9-d2386194b823)

**Comment by Yangaaa137** [comment]
it disappeared when I only kept the ESP function

**Comment by IntelSDM** [comment]
It is spamming the console because the server is trying to execute console commands to try and detect if you have the admin flag on or not. It is spamming commands like "Noclip" and if your stance changes it will instantly ban you.

**Comment by Yangaaa137** [comment]
> 它正在向控制台发送垃圾邮件，因为服务器正在尝试执行控制台命令以尝试检测您是否打开了管理员标志。它正在发送垃圾邮件命令，例如“Noclip”，如果您的立场发生变化，它将立即禁止您。

I see. thx a lot  :)
