### ISSUE TITLE
0/8 Bytes read

### ISSUE THREAD

**Issue by Xzeirox1** [IntelSDM/RustDMACheat#18]
I get this error when starting the .exe

[DMA @ 00:23:15]: loading libraries...
[DMA @ 00:23:15]: ERROR: could not load a library:
[DMA @ 00:23:15]: vmm: 00007FFEC7C90000

[DMA @ 00:23:15]: ftd: 0000000000000000

[DMA @ 00:23:15]: leech: 00007FFEDE470000

[DMA @ 00:23:15]: inizializing...
[DMA @ 00:23:15]: dumping memory map to file...
[DMA @ 00:23:15]: ERROR: Could not dump memory map!
[DMA @ 00:23:15]: Defaulting to no memory map!

**Comment by Xzeirox1** [comment]
i fixed it but now i get python 3.6 or higher not found

**Comment by Xzeirox1** [comment]
"Python initialization failed. Python 3.6 or later not found."

**Comment by Xzeirox1** [comment]
ok ima update myself again i fixed the python error

**Comment by Xzeirox1** [comment]
i get the 0/8 bytes read

**Comment by Xzeirox1** [comment]
so i have fixed this issue updated the offsets but get 0/8 bytes error

**Comment by Xzeirox1** [comment]
im new to this so i dont really know if the problem is on my end or in the code itself

**Comment by Xzeirox1** [comment]
got it to work how do i toogle features ?

**Comment by Xzeirox1** [comment]
i fixed it with just redoing some lines looking if i can somehow and a ui and chams ( admin flag is outdated probably )

**Comment by Xzeirox1** [comment]
if anyone can help me pls contact me on discord alcapone6249

**Comment by Rakeshmonkee** [comment]
admin flags shouldn't be outdated if you updated the offsets
