### ISSUE TITLE
Process or dma not connected

### ISSUE THREAD

**Issue by 4M6D** [IntelSDM/RustDMACheat#22]
rust is open and my dma is plugged in idk what is going on

**Comment by IntelSDM** [comment]
That is odd and I haven't ever had such a complaint before.  I would guess that you slept your pc, memprocfs doesn't work once a pc has been slept,

**Comment by 4M6D** [comment]
I know why now, its because of the cr3 decryption on eac.  You should update 1 more time pleaseeeee

**Comment by IntelSDM** [comment]
CR3 won't be causing PCILeech compatibility issues.

**Comment by 4M6D** [comment]
(Had to download the python 3.8 💀 )
