### ISSUE TITLE
Dma base?

### ISSUE THREAD

**Issue by spookykokojunge** [IntelSDM/RustDMACheat#25]
Hello are you planing on making a Dma base that people can use as a example on how to create Dma cheats ?
Because i have a hard time getting a food hold in the Dma seen.

**Comment by IntelSDM** [comment]
Hey mate, This is a base. If you want a simpler version then check the legacy branch.

**Comment by spookykokojunge** [comment]
Thank you for your fast reply. I'll explore the legacy branch as suggested. Regarding DMA cheating, I've grasped that PCILeech, Memproc, and the Dmalibary are necessary components for reading memory. However, I'm uncertain about the specific process of reading this information. I apologies for the many questions.

**Comment by spookykokojunge** [comment]
I found the example in https://github.com/Metick/DMALibrary/tree/Master/Example Still thanks for the fast answare i hope you continue updateing the cheat.
