### ISSUE TITLE
Failed to write Memory at 0x0000000000000008C

### ISSUE THREAD

**Issue by Ghostty1** [IntelSDM/RustDMACheat#28]
also Failed to write Memory at 0x00000000000000020
The cheat screen just goes white

**Comment by Ghostty1** [comment]
nvm I fixed the failed to write memory but when I load the cheat I only see the box esp on main screen but GUI Framework is white on the other screen

**Comment by IntelSDM** [comment]
The cheat is outdated. You must update it otherwise it will have issues.
