### ISSUE TITLE
Cheat ui not loading

### ISSUE THREAD

**Issue by 4M6D** [IntelSDM/RustDMACheat#29]
[LocalPlayer] Initialized
[LocalPlayer] LocalPlayer: 0x7FFBE0E57FF8
[LocalPlayer] Static Fields: 0x80110000
[LocalPlayer] Base Player: 0x0
[-] Failed to Execute Scatter Read
[MainCamera] Initialized
[MainCamera] MainCamera: 0x7FFBE0E91BC8
[MainCamera] Static Fields: 0x80110006
[MainCamera] Camera: 0x0
[MainCamera] CameraGamoObject: 0x0
[TODSky] Initialized
[TODSky] Class: 0x150000
[TODSky] Instance: 0x0 

It is getting some stuff but other stuff is invalid, the window for the cheat doesn't even show up and its just a console

**Comment by luminocityR** [comment]
Same for me, even though it worked last night after i updated offsets

**Comment by Ghostty1** [comment]
same

**Comment by IntelSDM** [comment]
The cheat is outdated. You must update it otherwise it will have issues.

**Comment by Rakeshmonkee** [comment]
the reason you are getting  errors like

```
[LocalPlayer] Base Player: 0x0

[MainCamera] Camera: 0x0

[MainCamera] CameraGamoObject: 0x0

[TODSky] Instance: 0x0
```

is because the offsets aren't updated properly. Make sure you are using the latest game version

IntelSDM has made a video showing how to update the offsets

**Comment by zekrui** [comment]
hey ive just updated the offsets, 90% sure all of the offsets are updated, but the ui still closes on launch
