### ISSUE TITLE
Unable to load FTD3XX.DLL 

### ISSUE THREAD

**Issue by sfdfgvdvdsvb** [IntelSDM/RustDmaCheat#3]
little confused by the error as i followed such instructions
![Capture](https://github.com/IntelSDM/RustDmaCheat/assets/106359677/7e211b2f-413a-4cc2-a346-47bc13f66c16)

**Comment by IntelSDM** [comment]
You need to put FTD3XX.dll into the application folder.

**Comment by sfdfgvdvdsvb** [comment]
i did that still same error

**Comment by IntelSDM** [comment]
I replicated your issue. By deleting FTD3XX.dll from the build directory.  
https://github.com/lambdaconcept/usbsniffer/blob/master/software/windows/FTD3XXLibrary/x64/FTD3XX.dll
Download it, put it next to the built exe.

**Comment by peludo-345** [comment]
![image](https://github.com/IntelSDM/RustDmaCheat/assets/104220882/4c8a9698-535d-403a-8ca1-1cd77cb1f0d7)
Im Still trying and isnt working idk why it says the same problem
