### ISSUE TITLE
GUI Framework just being white

### ISSUE THREAD

**Issue by Ghostty1** [IntelSDM/RustDMACheat#30]
The Cheat launches as normal but the only feature that works is box esp on main monitor and on the second monitor "GUI Framework" just goes white. But the console does not give any errors

**Comment by IntelSDM** [comment]
The cheat is outdated. You must update it otherwise it will have issues.

**Comment by Ghostty1** [comment]
I have updated everything tho and the esp wors normally but GUI framework is just white

**Comment by luminocityR** [comment]
I have the same issue after updating all offsets... No console errors but total white screen in GUI.

**Comment by Ghostty1** [comment]
@luminocityR if u find a solution pls lmk

**Comment by IntelSDM** [comment]
The GUI isn't showing because the playerlist is 0. You need to update the baseplayer static class.
