### ISSUE TITLE
No recoil not working

### ISSUE THREAD

**Issue by Ghostty1** [IntelSDM/RustDMACheat#32]
I updated everything and the cheat works perfectly but no recoil does not work at all, is there a way to fix that? Btw sorry for making so many issues :(

**Comment by IntelSDM** [comment]
You probably didn't update held entity or baseprojectile then.

**Comment by Ghostty1** [comment]
Will try doing that

**Comment by Ghostty1** [comment]
no both those are updated but it still doesnt work

**Comment by Ghostty1** [comment]
also console sometimes says "Failed to Execute scatter read" but the cheat still works, only recoil doesnt.

**Comment by IntelSDM** [comment]
The recoil properties field also needs updating.

**Comment by Ghostty1** [comment]
its up to date, its 0x2F0

**Comment by Ghostty1** [comment]
do I need to update the class above recoil properties?

**Comment by arlohewitt** [comment]
My fork that was just merged should all be updated properly, have a look at the SDK changes and you can try to figure out what you missed.

**Comment by Ghostty1** [comment]
hey, yeah I did and it works now, in Item ID I accidently put 10 instead of 20. Tysm for the help
