### ISSUE TITLE
GUI Rendering Library

### ISSUE THREAD

**Issue by sullivanb26** [IntelSDM/RustDMACheat#35]
Hey, I'm making a fork of your project for the use of the KMBox and other features, I was wondering what Library you used for rendering? Mainly so I can find examples of the tab controller as I'm trying to implement multiple tabs. Is it a custom library made by you? Or a public one with documentation? 
Thank you for your original project and hopefully answer :D
- A programmer

**Comment by Foolishware** [comment]
I think it's this one he has posted on his github
https://github.com/IntelSDM/GUI-Framework

**Comment by sullivanb26** [comment]
Thank you :)

**Comment by Foolishware** [comment]
> Thank you :)

No problem I'm excited to see all the evolving forks of this been messing around with it myself (mostly breaking everything) and having lots of fun with it lol
