### ISSUE TITLE
NoRecoil slider only changes the recoil a little bit

### ISSUE THREAD

**Issue by Glokk23** [IntelSDM/RustDMACheat#41]
instead of 0-100% recoil its more like 0-5% even with the slider all the way up it barely moves 

thought id go through all the recoil related offsets but couldn't find this one in Recoil Properties,

![image](https://github.com/IntelSDM/RustDMACheat/assets/71922108/2a0e3505-1018-438f-84db-c5bc8e2c6b60)

![image](https://github.com/IntelSDM/RustDMACheat/assets/71922108/160f134b-e2b9-4bcc-8b02-9f6be41921e5)

 i also checked all updated forks and none changed the RecoilProperties offset

**Comment by arlohewitt** [comment]
The offset is correct, its within the BaseProjectile class rather than the RecoilProperties.

![Capture](https://github.com/IntelSDM/RustDMACheat/assets/75036102/bfff151c-2221-4beb-a145-ddcae125ec4a)
