### ISSUE TITLE
Failed to Execute Scatter Read

### ISSUE THREAD

**Issue by wokonly** [IntelSDM/RustDMACheat#42]
Hello, I have been having a issue that when I run it it loads up and everything but then returns `Failed to Execute Scatter Read`, here is my full debug log for my issue and offsets are up to date as well. I am not the only one having this issue and it could just be that my build is broken but testing with different dma and also computers as well i get this issue

```
Debugging Window:
inizializing...
dumping memory map to file...
Dumped memory map!
FPGA ID: 12
DEVICE ID: 512
success!
[+] VMMDLL_ConfigGet ID = 12 VERSION = 0.0
<class 'vmmpyc.Vmm'> returned NULL without setting an exception
[+] Patched DTB
CR3 fixed
[+] Found Base Address for RustClient.exe at 0x00007FF6DAB30000
[+] Found Base Size for RustClient.exe at 0x00000000000A5000
Process information of RustClient.exe
PID: 27104
Base Address: 0x00007FF6DAB30000
Base Size: 0x00000000000A5000
[+] Found Base Address for GameAssembly.dll at 0x00007FFA570A0000
[LocalPlayer] Initialized
[LocalPlayer] LocalPlayer: 0x2000C75B
[LocalPlayer] Static Fields: 0x0
[LocalPlayer] Base Player: 0x0
[-] Failed to Execute Scatter Read
[MainCamera] Initialized
[MainCamera] MainCamera: 0x155E6E8B770
[MainCamera] Static Fields: 0x15CDC8827B0
[MainCamera] Camera: 0x15E99A18A20
[MainCamera] CameraGamoObject: 0x15E99947900
[TODSky] Initialized
[TODSky] Class: 0xC002DC93
[TODSky] Instance: 0x0
```

**Comment by IntelSDM** [comment]
Try Compiling in debug mode

**Comment by wokonly** [comment]
yeah still doing that i am not getting any errors that can tell me what the issue is, i am only getting `[-] Failed to Execute Scatter Read`
![image](https://github.com/IntelSDM/RustDMACheat/assets/84077549/0d959281-9790-4db9-8a2b-873bcb143347)

**Comment by Artorias000** [comment]
it dose this until your in a server then loads back up then you need to close and reopen every time you switch servers

**Comment by wokonly** [comment]
> it dose this until your in a server then loads back up then you need to close and reopen every time you switch servers

I get into a server with it open and i still get scatter read. I close and open it again and everything and still get the same error. what would be the issue?

**Comment by arlohewitt** [comment]
compile the latest repo - its up to date currently.

If you still get this issue, it might be a dodgy USB port or cable, i had a USB-C cable that would fail reads at random.

**Comment by wokonly** [comment]
> compile the latest repo - its up to date currently.
> 
> If you still get this issue, it might be a dodgy USB port or cable, i had a USB-C cable that would fail reads at random.

i dont have another usb-c on me but when doing test its able to get and read data from games like when i was using csgo radar it was working fine, could it be a dma card issue if not usb or a pc issue?

**Comment by arlohewitt** [comment]
are you sure you are running it after loading into a rust server? i can replicate this exact chain of messages by running the program while in a loading screen.

**Comment by wokonly** [comment]
> are you sure you are running it after loading into a rust server? i can replicate this exact chain of messages by running the program while in a loading screen.

yeah i load into the server i walk around and i run it and get the error

**Comment by arlohewitt** [comment]
yeah thats really strange, ive updated the repo again earlier today so if you rebuild it will be up to date again.


`Debugging Window:
inizializing...
dumping memory map to file...
Dumped memory map!
FPGA ID: 4
DEVICE ID: 1536
success!
[+] VMMDLL_ConfigGet ID = 4 VERSION = 0.0
CR3 fixed
[+] Found Base Address for RustClient.exe at 0x00007FF7EAB60000
[+] Found Base Size for RustClient.exe at 0x00000000000A8000
Process information of RustClient.exe
PID: 31516
Base Address: 0x00007FF7EAB60000
Base Size: 0x00000000000A8000
[+] Found Base Address for GameAssembly.dll at 0x00007FFF18590000
[LocalPlayer] Initialized
[LocalPlayer] LocalPlayer: 0x1FDB0AAB280
[LocalPlayer] Static Fields: 0x1FD83F1DC60
[LocalPlayer] Base Player: 0x0
[-] Failed to Execute Scatter Read
[MainCamera] Initialized
[MainCamera] MainCamera: 0x1FDB24E4030
[MainCamera] Static Fields: 0x1FD83ED7960
[MainCamera] Camera: 0x0
[MainCamera] CameraGameObject: 0x0
[TODSky] Initialized
[TODSky] Class: 0x1FDB2AB2BB0
[TODSky] Instance: 0x0`

Here is my console when running on the latest build (afk on menu). It basically matches your error, when i am in a server, it will load up the overlay window and GUI just fine. The only thing i can spot, but only in your first message is "<class 'vmmpyc.Vmm'> returned NULL without setting an exception" - maybe you haven't properly downloaded and installed python to PATH?

**Comment by wokonly** [comment]
im on python verison 3.8, is that the correct version or should i be on a newer version because that could be causing the issue yeah

**Comment by arlohewitt** [comment]
I am also on 3.8, i just followed the guide in the [Instructions.md](https://github.com/IntelSDM/RustDMACheat/blob/master/Instructions.md)

**Comment by wokonly** [comment]
> I am also on 3.8, i just followed the guide in the [Instructions.md](https://github.com/IntelSDM/RustDMACheat/blob/master/Instructions.md)

Hey, i was able to fix it and everything is working good. It was something wrong with my cord because other cheats for cs2 now work as well but using the rust cheat when playing it would randomly crash the cheat out of no where leaving me with just admin boxs and no recoil. Why would this happen?

**Comment by sanzgaa** [comment]
hi, im having same problem, how did u fix?
