### ISSUE TITLE
Are features like Bright Night unsafe to use?

### ISSUE THREAD

**Issue by CrazyTaxiLA** [IntelSDM/RustDMACheat#44]
Are features like Bright Night unsafe to use? Will the hammer come down on you? Or can you use them, assuming the server doesn't have a plugin to block it?

**Comment by IntelSDM** [comment]
It is safe to use.

**Comment by CrazyTaxiLA** [comment]
But doesn't it set the admin flag?

**Comment by IntelSDM** [comment]
Bright night doesn't set admin flag.

**Comment by CrazyTaxiLA** [comment]
Does AdminTime set the flag, I assume yes. Maybe I got them mixed up.

**Comment by IntelSDM** [comment]
No, It doesn't set admin flag. Its purely through Cvars.

**Comment by CrazyTaxiLA** [comment]
Interesting. Ty for the answers. Appreciate it.
