### ISSUE TITLE
Can't Find Meaning?

### ISSUE THREAD

**Issue by CrazyTaxiLA** [IntelSDM/RustDMACheat#45]
In MainCamera.h, it says "Can't find" in the comment. What's that mean and if they can't be found, how to find these values?

uint64_t CameraGameObject = 0x10; //cant find
uint64_t ViewMatrixOffset = 0x2E4; //cant find

**Comment by IntelSDM** [comment]
These are from the unity native backend. You need to use IDA or Cheat engine if you want to find them. They are very unlikely to change.

**Comment by CrazyTaxiLA** [comment]
Any chance you can update it for us on the repo, just those two lines? Would appreciate it if you could or had the time to.

**Comment by IntelSDM** [comment]
Those 2 offsets are still up to date.

**Comment by CrazyTaxiLA** [comment]
Interesting, the comment should be removed in that case. Thanks for your help. Sorry for wasting your time!

**Comment by IntelSDM** [comment]
The comments would be from arlohewitt as he has been doing a great job spending some of his free time maintaining the free version of the cheat.

**Comment by CrazyTaxiLA** [comment]
Yes I appreciate his help too! Thank you arlohewitt.

**Comment by arlohewitt** [comment]
Thanks for the correction, my fork now has a better comment for the //cant find MainCamera.h
along with an rather lengthy explanation for // Not sure about these ones, I copied from a chain
which was in BaseNetworkable.h.
They will be in my next pull request whenever rust next updates!
