### ISSUE TITLE
New Native Offsets

### ISSUE THREAD

**Issue by IntelSDM** [IntelSDM/RustDMACheat#48]
The game did a unity update. I can't be bothered updating this repo right now.
Since some people will struggle to update native offsets for the camera; here are the new camera offsets:
```c++
class MainCamera
{
	/*
	Script.json
	"Address": 55074032,
	  "Name": "MainCamera_TypeInfo",
	  "Signature": "MainCamera_c*"
	*/
	uint64_t Class = 0x3AB9E00;
	//Dump.cs / DummyDLL
	uint64_t StaticField = 0xB8; // Static Padding To Access Static Fields
	uint64_t Camera = 0x0; // public static Camera mainCamera
	uint64_t CameraGamoObject = 0x10;
	uint64_t ViewMatrixOffset = 0x30C;
```
All the other offsets can be retrieved with il2cpp dumper.

**Comment by arlohewitt** [comment]
opening my pull request with everything updated now. Of course viewmatrix changes one update after I comment that its unlikely to 🤣.

**Comment by IntelSDM** [comment]
Good job. The viewmatrix was the same for about 3 years. It will probably stay at 0x30C for at least a year.

**Comment by kodiz11** [comment]
hi my friend i have 1 question for this is undected on rust official ?steam or we must do something to be undexted like kernel ?
