### ISSUE TITLE
Basenetworkable usage??

### ISSUE THREAD

**Issue by Bishbash777** [IntelSDM/RustDMACheat#54]
Hello, is there a reason why do don't do anything with basenetworkable entities such as ores etc?

**Comment by IntelSDM** [comment]
The point of the software is to provide an alternative to paid cheats for some people but mainly to allow people to learn from it. There are plenty of resources in the cheat for you to easily be able to iterate basenetworkable, I even include the class name so you can bypass the guarded regions on it by EAC.

**Comment by Bishbash777** [comment]
Thanks for the reply. I already use it for guidance rather than a pasta. I was just wondering why include it if not used.
