### ISSUE TITLE
Insta ban

### ISSUE THREAD

**Issue by km05pu05** [IntelSDM/RustDMACheat#57]
After using this program its draws esp box on gaming pc no on 2nd pc… got insta ban

**Comment by uruskan** [comment]
Well, it's publicly available on the Github and it's been like this for a long time. What did you expect? You can use this completely UD with very little time consuming enc and changes.

**Comment by Rakeshmonkee** [comment]
it is most likely the firmware you are using on the DMA

**Comment by Rakeshmonkee** [comment]
> After using this program its draws esp box on gaming pc no on 2nd pc… got insta ban

It is most likely the firmware you are using that is detected

**Comment by km05pu05** [comment]
Firmware is 1:1 with full emulation

**Comment by Rakeshmonkee** [comment]
> Firmware is 1:1 with full emulation

who did you buy fw from?

**Comment by km05pu05** [comment]
Created myself following this guide https://github.com/Silverr12/DMA-CFW-Guide

**Comment by Rakeshmonkee** [comment]
> Created myself following this guide https://github.com/Silverr12/DMA-CFW-Guide

you did the 1:1 coe and included bars in bar4k.coe file?

**Comment by km05pu05** [comment]
Yes

**Comment by Rakeshmonkee** [comment]
> Yes

seems like a you issue. the cheat works for me, and has been for the past couple months. not a single ban by EAC

what device are you emulating and is there a yellow icon in device manager?

**Comment by km05pu05** [comment]
I guess not but I’m at work I will confirm when arrive at home

**Comment by Rakeshmonkee** [comment]
> I guess not but I’m at work I will confirm when arrive at home

![image](https://github.com/IntelSDM/RustDMACheat/assets/89455475/3e634e99-4142-4c99-b4cf-6e2eef86c05b)


just to be clear, you edited both of these files with the correct values from your donor card?

**Comment by km05pu05** [comment]
Yes bar was 1mega not 4k

**Comment by Rakeshmonkee** [comment]
> Yes bar was 1mega not 4k

rakeshmonkee

add me on discord when you get home, and we'll go from there

**Comment by Sl1p3r** [comment]
Im new to the DMA community, does this cheat need the KMBOX? I only want the recoil from this cheats not the esp, also does this cheat write to the memory or the main pc never gets writen only read? Also where should i get the Firmware for rust ??

**Comment by arlohewitt** [comment]
you dont need a KMBOX for this cheat to work, the no recoil is achieved by writing to various areas in memory to reduce recoil.
Most of the features other than esp are achieved by writing to memory.

Build your own firmware following github [guides](https://github.com/Silverr12/DMA-CFW-Guide)

**Comment by Sl1p3r** [comment]
And is that less detectable then a simple script?

**Comment by Rakeshmonkee** [comment]
> And is that less detectable then a simple script?

If your firmware is good, yes

**Comment by Sl1p3r** [comment]
Can j get your discord to make a few questions?
