### ISSUE TITLE
Got banned by EAC after today's update (and no, I have good personal firmware).

### ISSUE THREAD

**Issue by MaRf1Mm** [IntelSDM/RustDMACheat#58]
Used write functions, so it's not so big of a surprise. Just a warning to all other people who use this - be careful.

**Comment by arlohewitt** [comment]
Could you provide more info? 

I feel like this is more likley to be a manual ban if you are certain your firmware is good,
the only bans that this has caused me is a single server ban, caused by adminflag detections with bundled commands.

**Comment by MaRf1Mm** [comment]
Played the last 3 days with my friend on a modded server, was using admin box, a little bit of no recoil, and one time tried using debug camera with fake admin but they blocked it so I stopped. Nothing special, just basic stuff. I wasn't reported either. As I was more of a base builder than a fighter this wipe. So yeah, I have zero clue what might have caused it, but after the latest update I was AFK in base and suddenly got EAC'd, so yeah ¯\_(ツ)_/¯

**Comment by IntelSDM** [comment]
It only writes to mutable pages that can't be CRCed. The cheat itself isn't detected.  It is likely firmware, there have been plenty of firmware ban waves recently. Atomics firmware got hit repetitively, diviners emulation stuff also got hit.

**Comment by uruskan** [comment]
> It only writes to mutable pages that can't be CRCed. The cheat itself isn't detected. It is likely firmware, there have been plenty of firmware ban waves recently. Atomics firmware got hit repetitively, diviners emulation stuff also got hit.

Indeed thats probably the case

**Comment by spookykokojunge** [comment]
Same happend for me but do you also get banned if you jsut have your dma card in and its detected ore only if it writes/reads memory out of that game ?

**Comment by IntelSDM** [comment]
> Same happend for me but do you also get banned if you jsut have your dma card in and its detected ore only if it writes/reads memory out of that game ?

Did that happen today? If so what firmware were you using? I had a Russian telling me he also got banned today but he couldn't really communicate what firmware he used.  

Also, they detect the card being plugged into the machine. It doesn't matter if you are actively using it or not.

**Comment by spookykokojunge** [comment]
> > Same happend for me but do you also get banned if you jsut have your dma card in and its detected ore only if it writes/reads memory out of that game ?
> 
> Did that happen today? If so what firmware were you using? I had a Russian telling me he also got banned today but he couldn't really communicate what firmware he used.
> 
> Also, they detect the card being plugged into the machine. It doesn't matter if you are actively using it or not.

I played for about two days with my card plugged in and not reading/writing, and then today I got banned ten minutes after I injekted. The weird part is that before I got banned, I played with those cheats for about two hours without any problems earlyer that day.

**Comment by spookykokojunge** [comment]
Im currently using my preflashed fw from sugargoo and i have no idea where i should get a good cheap fw as most fw sellers are scamming. Can you link me some seller that you maybe got you fw from ?
