### ISSUE TITLE
need help finding these new id's

### ISSUE THREAD

**Issue by mesaruk** [IntelSDM/RustDMACheat#64]
case 54612: //ak
weaponNum = 1;
break;

do you know how sullivan is finding these i can only find the longer number which changes when you die or log. also how do you find the offset for static class?

**Comment by IntelSDM** [comment]
Grab the name instead and then you won't have to update it.

**Comment by mesaruk** [comment]
ah ok, you adding anymore features soon, like nodes esp etc?
