### ISSUE TITLE
The EXE was removed

### ISSUE THREAD

**Issue by k2-cell** [IntelSDM/RustDMACheat#65]
Exe file is no longer there as shown in guide, then running the code in visual studio I keep getting 3 errors trying to compile and run the main.cpp

**Comment by k2-cell** [comment]
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\cadel\OneDrive\Desktop\DM (1)\RustDMACheat-master\RustDMA\main.cpp).

cannot open source file "iostream" (dependency of "pch.h"). Please run the 'Select IntelliSense Configuration...' command to locate your system headers.

cannot open source file "dwmapi.h"

**Comment by k2-cell** [comment]
(1)\RustDMACheat-master\RustDMA\g++" does not exist.

**Comment by arlohewitt** [comment]
I never meant to upload the .exe, you shouldnt trust executables from github repo's instead read the code and compile yourself.

As for your compilation issues, i am personally using vistual studio community 2022
17.10.2 with desktop c++ and windows c++ .

if you replicate that it should compile fine.
