### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Cl1cker0** [IntelSDM/RustDmaCheat#69]
>C:\Users\Cl1cker\Downloads\RustDMACheat-master\RustDMA\Misc\Pch\Pch.h(80,10): error C1083: Cannot open include file: 'Colour.h': No such file or directory
1>  (compiling source file 'SDK/TODSky.cpp')
  
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Build failed.

**Comment by Cl1cker0** [comment]
could i have your discord perhaps you could help me, please, all i want is have admin flag and thats all i ever wanted

**Comment by Cl1cker0** [comment]
i swear ill even pay u lol, i just want a little bit of code that will give me admin flag, thats all i ever want

**Comment by Rakeshmonkee** [comment]
> > C:\Users\Cl1cker\Downloads\RustDMACheat-master\RustDMA\Misc\Pch\Pch.h(80,10): error C1083: Cannot open include file: 'Colour.h': No such file or directory
> > 1>  (compiling source file 'SDK/TODSky.cpp')
> 
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== Build failed.

Try placing the RustDMACheat-master Directory onto your desktop, then retry building the solution. but I believe the type needs to be on release and x64

**Comment by IntelSDM** [comment]
This is due to it being built within the wrong build settings that the project isn't set up for. Due to this the project can't find the included header files.
