### ISSUE TITLE
DMA: failed to Execute Scatter Read

### ISSUE THREAD

**Issue by homi231** [IntelSDM/RustDmaCheat#7]
hey since i use this i have [DMA @ 15:48:04]: failed to Execute Scatter Read and since that i cant even craft stuff at the workbench

**Comment by IntelSDM** [comment]
That's normal, it's just trying to read if you have a weapon out and then reads for the base projectile but can't find it. The incapability to crash at the workbench is most likely due to the lack of checks on the recoil write, I will fix that when I am finished with some other stuff.

**Comment by homi231** [comment]
ah okay so i can confirm its bc of that nice will disable no recoil do the trick ? cause i just need the esp cause the server is full of cheaters haha

**Comment by IntelSDM** [comment]
Yeah just disable no recoil. If you want you can just fix the issue by doing lots of null checks on pointers to make sure they aren't 0.  I will probably go through and make a hashmap of the weapons based on ID so i can just flash which ones contain a valid base projectile. Thats for another time though, For now, you just need to make sure that baseprojectile and recoil properties aren't null.

**Comment by homi231** [comment]
> Yeah just disable no recoil. If you want you can just fix the issue by doing lots of null checks on pointers to make sure they aren't 0. I will probably go through and make a hashmap of the weapons based on ID so i can just flash which ones contain a valid base projectile. Thats for another time though, For now, you just need to make sure that baseprojectile and recoil properties aren't null.

hey thx really for the awnser im. i would love to take that offer and do it myself and provide it to you but unfortunatly im not that far into Programing and Reverse engineering in general. i think i could do the offset updates but thats about it. if you have some lecture for me to read or a directory to point me too im greatfull to read and learn it and try it out myself.

**Comment by IntelSDM** [comment]
The issue with workbenchs was caused by the admin flag being set constantly preventing the workbench flag. I have changed it to a one-time variable.
